# The main structure that we have to remember is 
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: myconfig
# data:
#   key1: value1
#   key2: value2

apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfig
data:
  APP_MODE: "production"
  LOG_LEVEL: "debug"
